// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lib_wire/mission"
	"lib_wire/monster"
	"lib_wire/player"
)

import (
	_ "lib_wire/env"
)

// Injectors from wire.go:

func InitMission() *mission.Mission {
	playerPlayer := player.New()
	monsterMonster := monster.New()
	missionMission := mission.New(playerPlayer, monsterMonster)
	return missionMission
}
