// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(args1 monsterArgs, args2 playerArgs) *EndingA {
	mainPlayer := newPlayer(args2)
	mainMonster := newMonster(args1)
	endingA := NewEndingA(mainPlayer, mainMonster)
	return endingA
}

func InitEndingB(args1 monsterArgs, args2 playerArgs) *EndingB {
	mainPlayer := newPlayer(args2)
	mainMonster := newMonster(args1)
	endingB := NewEndingB(mainPlayer, mainMonster)
	return endingB
}

// wire.go:

var monsterPlayerSet = wire.NewSet(newPlayer, newMonster)
