basePath: /api/v1
definitions:
  model.User:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: demo for swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: swagger-demo
  version: "1.0"
paths:
  /user/login:
    post:
      description: user login
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/model.User'
      summary: user login
      tags:
      - user
  /user/logout:
    get:
      description: user logout
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: 退出是否成功
          schema:
            type: boolean
      summary: user logout
      tags:
      - user
swagger: "2.0"
